### ISSUE TITLE
Issue with Friends

### ISSUE THREAD

**Issue by ServerCrashes** [didjee2/BungeeUtilisals#1]
When adding a friend, hovering over Accept does nothing, hovering over Deny has accept's command, and in the empty space next to Deny has Deny's commands.
![2016-02-15_13 17 54](https://cloud.githubusercontent.com/assets/17256913/13057076/bb185476-d3e7-11e5-94b1-c3fba21cc9f3.png)
![2016-02-15_13 17 51](https://cloud.githubusercontent.com/assets/17256913/13057078/bebacd02-d3e7-11e5-8e89-3dc975705492.png)

**Comment by didjee2** [comment]
I'll take a look at it.
But can you send your friends.yml file?
In a pastebin or hastebin please.

**Comment by ServerCrashes** [comment]
http://pastebin.com/ZX6nzT8U

**Comment by didjee2** [comment]
I'll take a look to it. I don't know the problem yet.

**Comment by ServerCrashes** [comment]
Alright, thanks!

**Comment by didjee2** [comment]
This issue has been fixed together with v2.1.3.
Thanks for reporting this issue!
