### ISSUE TITLE
Swear bypass

### ISSUE THREAD

**Issue by killkillsito** [didjee2/BungeeUtilisals#12]
If u put any word on your config of antiswearyng.
Per example: "Hello". If you write "hello" with/or modifyng capital letters you can easily bypass this. You only recieve the message from the config but the plugin doen't cancel the word.
And there is not permission to bypass this, for example to add to network owners.

**Comment by didjee2** [comment]
This bug has been fixed in BungeeUtilisals version [219](https://www.spigotmc.org/resources/bungeeutilisals.7865/update?update=105009).
