### ISSUE TITLE
Messaging not working

### ISSUE THREAD

**Issue by cervinakuy** [didjee2/BungeeUtilisals#14]
[Here](http://hastebin.com/kiyiruwoqa.avrasm) is the error.

Please fix, and also, instead of /gmsg, could you just make it /msg?

Thanks!

**Comment by didjee2** [comment]
This issue has been patched in version #216.
For the /gmsg to /msg, this can be easily changed in the config, at least added.
Just add 'msg' in the aliases list of the MSG command.

Thanks for reporting this bug!
