### ISSUE TITLE
A few issues and suggestions.

### ISSUE THREAD

**Issue by cervinakuy** [didjee2/BungeeUtilisals#15]
Hey!

So I love your plugin, however it has some bugs, could you please fix them? I've also added some of my own suggestions at the bottom which would be awesome if you could add them :).

BUGS:
1. /vote doesn't work.
2. /report toggle doesn't work.
3. /friend deny doesn't work.
4. For some reason it says in the bans.yml that the command to view player information is /pinfo when it's /binfo. Could you change it in the config.yml as well as the command itself? I think /pinfo makes more sense.
5. Where is the msg message configurable? Along with the not enough /msg arguments message?
6. When you type /reports 0, it gives an internal error.
7. The first report does not save, so when I type /reports 1, it doesn't display and says there aren't any reports. But when I report a second time, and type /reports 1, it displays, but not the first one. Only the 2 second one.
8. /friend add with no third argument does nothing, please make it send a message saying it needs more arguments.
9. /friend add [your own name] gives an internal error.
10. /friend remove with no third argument does nothing, please make it send a message saying it needs more arguments.
11. /friend [something random] does nothing, please make it send a message saying it needs more arguments.
12. /friend accept [your own name] gives an internal error.
13. /party [something random] does nothing, please make it send a message saying it needs more arguments.
14. /party admin with no third argument does nothing, please make it send a message saying it needs more arguments.
15. Where is the /gspy message configurable?

SUGGESTIONS:
1. Can you change /butilisals lock to have an alias of /chat toggle?
2. Could you add /lspy or /localspy to spy on local commands?
3. A Hub balancer would be AMAZING for my server, and I'm sure it would be for many other networks as well, please add it! :D

QUESTIONS:
1.  What does the Players section in the reports config do?
2. Where can I find a list of all the placeholders I can use for the tab manager?

Thank you,
- Cervinakuy

**Comment by didjee2** [comment]
Let's make a list ;):

BUGS:
1) What doesn't work of it? Just no command? Are there any errors? Did you enabled the Vote Command in the config?
2+3+6+7+8+9+10+11+12+13+14) The friend, party & report system is being recoded. They are all not working correctly right now.
4) /pinfo will be added as an ALIAS in version 217.
5+15) These messages are not configurable (yet).

SUGGESTIONS:
1) Will be added in version 217.
2) Will be added in version 217.
3) Will be added soon. I don't know which version yet.

QUESTIONS:
1) I don't remember exactly anymore lol. It has to be recoded, it will be gone then :+1:.
2) There are only 4 Placeholders right now:
    - %p%
    - %server%
    - %globalonline%
    - %nl% or %newline%
They explain themselves I think. I'm working on something like a Bungeecord PlaceHolderAPI right now. (Which BungeeUtilisals is going to support).

**Comment by cervinakuy** [comment]
BUGS:

1) Voting is now working, I'm not sure what the issue was before, but it's fixed.

4) Perfect, just what I was looking for :).

SUGGESTIONS:

1 +2) Awesome.

3) Okay, this would be perfect for my server, so whenever you have the time to add it please do :).

QUESTIONS:

1)  XD, okay then lol.

2) I'm not sure where it's located on the overview page, but please add it there, or else more people won't know the placeholders.

And if you will do a BungeeCord Placeholder API, will it be built in or simply separate? Please make it separate because I don't use much of the placeholders and I don't want to add another Proxy plugin or else it'll slow it down, since it wouldn't be used.

No problem, thank you so much for taking some of my suggestions and fixing those bugs, I appreciate it :).

**Comment by didjee2** [comment]
The placeholder api would have alot of place holders of different bungee plugins, f.e. RedisBungee.
But they are not required to be in it. Only BungeePlaceholders & BungeeUtilisals would have to be in it.

**Comment by cervinakuy** [comment]
Oh okay.
