### ISSUE TITLE
Bugs | AntiSwear not working correct

### ISSUE THREAD

**Issue by partydragen** [didjee2/BungeeUtilisals#17]
AntiSwear only register the first blocked word :/
this is not full list but only the word on top being registred the other not working
  Blocked:
  - 'faen'
  - 'fuck'
  - 'fuckers'

and on message its stand '&cPlease do not swear!' with a color but when i swear its white text

**Comment by didjee2** [comment]
This bug has been fixed in BungeeUtilisals version [219](https://www.spigotmc.org/resources/bungeeutilisals.7865/update?update=105009).
