### ISSUE TITLE
Ban/Mute & internal error

### ISSUE THREAD

**Issue by Padlick** [didjee2/BungeeUtilisals#19]
At /unban, if a player is banned and I unbanned him, the plugin says "Player unbanned", but the message "That player is not banned" comes too. This is not only at ban, at mute and other it comes too.

At /friend add PLAYER, if the player is offline, there comes an internal error, not the message "That player is not online".

Sorry for my bad english, I am german.

**Comment by didjee2** [comment]
The Friend system has to be recoded.
And what version are  you using?
That /unban bug should be fixed in version 221. (I'm not sure).

**Comment by Padlick** [comment]
I am using the lattest version (221).

**Comment by Padlick** [comment]
Here is a little evidence:
23:47:49 [INFORMATION] System » xCrayzz wurde zeitgebannt! Grund: Test
>unban xCrayzz
23:48:17 [INFORMATION] System » xCrayzz wurde entbannt!
23:48:17 [INFORMATION] System » Dieser Spieler hat keinen Bann!
