### ISSUE TITLE
Cannot type commands with dots or bad words.

### ISSUE THREAD

**Issue by cervinakuy** [didjee2/BungeeUtilisals#21]
Hello!

So whenever I try to add a perm for example /pex group Member add some.permission.node it says do not advertise and I'm forced to run it from console, which is a HUGEEEE pain.

Also, if I do something like /give cervinakuy compass 1 it says do not swear and I can't give myself the item. PLEASE FIX!

Thanks,
Cervinakuy

**Comment by didjee2** [comment]
About advertise, I'll make it so it ignores commands, and about /give, you added ass in the block list and advanced is on true I think.

**Comment by cervinakuy** [comment]
Please make it so advanced doesn't block words in commands. Or else like I said I can't do /give cervinakuy compass.

Thanks!
