### ISSUE TITLE
A list of bugs

### ISSUE THREAD

**Issue by partydragen** [didjee2/BungeeUtilisals#22]
Bugs List: (Please fix the 3 bugs i listed first)
* gspy state "/gspy" still not working always disabled when we relog
* gspy permission "butilisals.gspy" not working
* People can still use msg self them are muted
* when we tempmute players its always stand "never" on unmute time on /pinfo
* When we unban players its stand "That player is not banned!" when se using UUID mode but them still being unbanned :)

Github
Add recent update to github

**Comment by didjee2** [comment]
These should be fixed
