### ISSUE TITLE
Error on every command, MySQL error and no admin bypass

### ISSUE THREAD

**Issue by killkillsito** [didjee2/BungeeUtilisals#25]
Hey, im using BungeeUtilisals for a long time in my network, and i've found some bugs:
First:
Error on every single command:
When u type any command (Bungee or Spigot ones) u get a console error log:
https://gyazo.com/6b9e18cde008b5322d72191fb4e6e824
![first1](https://cloud.githubusercontent.com/assets/19974310/19618385/51c92d02-9849-11e6-8696-1c41fcfce42a.PNG)

Second:
Error when mysql is not active:
When u have not active the mysql option, when a player join the server, u get a console error log:
https://gyazo.com/2dc0678b863b5993eb6ebb42c0745961
![mysql](https://cloud.githubusercontent.com/assets/19974310/19618390/77b6d870-9849-11e6-8bb4-116412a920e5.PNG)

And theres not any permission to bypass all for the admins or owners

**Comment by didjee2** [comment]
Fixed some versions before already ...
Forgot to answer & close the issue, sorry for that.
