### ISSUE TITLE
No Permissions to anything?

### ISSUE THREAD

**Issue by RoyalPrison** [didjee2/BungeeUtilisals#29]
**Hi Didjee2**
I loooove this plugin for Bungeecord, But it could be really nice if you could do so Op's as all permissions becuse i cant do anything and i read the instructions from the Spigot page of yours, but i still cant do nothing.

Please help me.

**Comment by RoyalPrison** [comment]
And yes i tryed to give med permission node "butilisals.*" and "butilisals.admin.*" and set the Bukkit Permission=true that doesnt work.

And i tryed giving the same permissions ind the bungeecord config file too admins doesent work either.

This doesnt make any sense.

**Comment by didjee2** [comment]
Did you also add the BungeeUtilisals plugin in your Bukkit server?
This is needed in order to respond to the BungeeUtilisals request.

**Comment by RoyalPrison** [comment]
Yes, i did try that and its still bugged the hole thing doesent seem to work at all... :(
