### ISSUE TITLE
Connection Messages when using /server

### ISSUE THREAD

**Issue by ajbboy123** [didjee2/BungeeUtilisals#3]
These messages have always been an issue with BungeeUtilisals and I didn't mind it at first, but now it just looks sort of messed up and stupid.

When I'm in the Lobby, and I do /server vanilla, then do /server: http://i.imgur.com/ZtfDeo5.png

I do /server again to show you that I didn't change Servers, and I'm NOT in the vanilla server already.

**Comment by ajbboy123** [comment]
Also, to add to this, can you make it so it doesn't send the message as soon as you do the command, can you make it so say if I do /server factions it would send me to the Server, confirm that I'm on the factions Server, and then says "You have been connected to Factions"

**Comment by didjee2** [comment]
Can you explain it a bit more? I don't really understand it all :/

**Comment by didjee2** [comment]
Expired ticket
