### ISSUE TITLE
Bug tempmute

### ISSUE THREAD

**Issue by DUDU54330** [didjee2/BungeeUtilisals#30]
I execute this command "/tempmute mrtroll 1m test"

player see this so it's correct
![image](https://user-images.githubusercontent.com/14166148/35783363-036ff160-0a06-11e8-920c-a0417ab6f970.png)

but with the command "/binfo" the tempmute time is not correct
![image](https://user-images.githubusercontent.com/14166148/35783376-32a0784c-0a06-11e8-9d44-2b16daf331e6.png)

I also noticed that a muted player could not do "/warp" is this normal?

**Comment by didjee2** [comment]
I would have to check for /warp if muted (when I get online).

Could you search the tempmute in your punishments table in mysql?

**Comment by DUDU54330** [comment]
here is the Mutes table
![image](https://user-images.githubusercontent.com/14166148/35795709-4edf8832-0a5a-11e8-9f07-efd461ccbfc8.png)

I saw that the number in "MuteTime" is a micro time not a timestamp, i don't know if that is the problem

**Comment by didjee2** [comment]
That’s probably why /warp is blocked yes. I’ll change that, I’ll also fix the mute time (found the issue).

I’ll try to fix it in a few hours.

**Comment by DUDU54330** [comment]
thanks :)

**Comment by didjee2** [comment]
Should be fixed in Build 228.
