### ISSUE TITLE
Staff can't see Staffchat until they've talked in it at least once

### ISSUE THREAD

**Issue by ajbboy123** [didjee2/BungeeUtilisals#4]
So I haven't needed to use Staffchat for a while, but when I went to use it yesterday, my other Staff Couldn't see the Staffchat messages I was sending. They can only see the Staffchat once they have spoken in Staffchat at least once, and this seems to reset after we reboot our Proxy Server.

**Comment by didjee2** [comment]
This should be fixed in version 215, which is just released.
