### ISSUE TITLE
A error that some times coming on console

### ISSUE THREAD

**Issue by partydragen** [didjee2/BungeeUtilisals#5]
23.04 16:54:15 [Server] SEVERE com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'IP' at row 1
23.04 16:54:15 [Server] SEVERE at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3885)
23.04 16:54:15 [Server] SEVERE at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823)
23.04 16:54:15 [Server] SEVERE at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
23.04 16:54:15 [Server] SEVERE at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
23.04 16:54:15 [Server] SEVERE at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2526)
23.04 16:54:15 [Server] SEVERE at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1618)
23.04 16:54:15 [Server] SEVERE at com.mysql.jdbc.StatementImpl.executeUpdate(StatementImpl.java:1549)
23.04 16:54:15 [Server] SEVERE at com.dbsoftware.bungeeutilisals.bungee.utils.PlayerInfo.putPlayerInTable(PlayerInfo.java:36)
23.04 16:54:15 [Server] SEVERE at com.dbsoftware.bungeeutilisals.bungee.punishment.listeners.LoginListener.onLogin(LoginListener.java:18)
23.04 16:54:15 [Server] SEVERE at sun.reflect.GeneratedMethodAccessor6.invoke(Unknown Source)
23.04 16:54:15 [Server] SEVERE at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

**Comment by didjee2** [comment]
This should be fixed in version 215, which is just released.
